config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :companies do 
    collection do
        post 'add_employee'
      end
  end
  resources :sms
  

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates_uniqueness_of :title
  has_many :employees, dependent: :destroy
  MAPPING = {
    	"name" => "name",
    	"number" => "number"
  	}
	before_save :format_number
	
	def format_number; end

    def self.import(file, company_id)
      spreadsheet = open_spreadsheet(file)
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        row.keys.each { |k| row[ MAPPING[k] ] = row.delete(k) if MAPPING[k] }
        Company.transaction do 
          employee = Employee.create(name: row['name'], number: row['number'], company_id: company_id)
        end
      end
  	end
  
  	#helper method for import
  	def self.open_spreadsheet(file)
    	case File.extname(file.original_filename)
	      when ".csv" then Roo::CSV.new(file.path, file_warning: :ignore)
	      when ".xls" then Roo::Excel.new(file.path, file_warning: :ignore)
	      when ".xlsx" then Roo::Excelx.new(file.path, file_warning: :ignore)
	      else raise "Unknown file type: #{file.original_filename}"
	    end
  	end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	belongs_to :compnay
	validates_presence_of :name, :number, :company_id
	before_save :format_phone, if: :number_changed?

	def format_phone
		phone = self.number.present? ? phone_formatter(self.number) : nil
    	assign_attributes(number: phone)
	end
		
  private

	def phone_formatter(phone)
      if phone[0] == "0"
        puts "1"
        phone = "+92" + phone[1..-1]
      elsif phone[0] == "9"
        puts "2"
        phone = "+" + phone
      elsif phone[0..1] == "+0"
        puts "3"
        phone = "+92" + phone[2..-1]
      elsif phone[0..1] == "+3"
        puts "4"
        phone = "+92" + phone[1..-1]
      elsif phone[0] == "3"
        puts "5"
        phone = "+92" + phone[0..-1]
      elsif phone[0..3] == "+920"
        puts "6"
        phone = "+92" + phone[4..-1]
      else
        puts "7"
        phone = phone[0..-1]
      end
      return phone
    end
end

app/models/sm.rb
class Sm < ActiveRecord::Base
	validates_presence_of :to, :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   protected
    def after_sign_in_path_for(resource)
      sms_path
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @employees = @company.employees
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_employee
    @company = Company.find(params[:company_id])
    Company.import(params[:file], params[:company_id])
    redirect_to @company
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:title, :package)
    end
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sm, only: [:show, :edit, :update, :destroy]

  # GET /sms
  # GET /sms.json
  def index
    @sms = Sm.all
  end

  # GET /sms/1
  # GET /sms/1.json
  def show
  end

  # GET /sms/new
  def new
    @sm = Sm.new
  end

  # GET /sms/1/edit
  def edit
  end

  # POST /sms
  # POST /sms.json
  def create
    @sm = Sm.new(sm_params)
    employees = Company.find(params[:sm][:to]).employees
    employees.each do |emp|
      url = generate_url(@sm, emp)
      Unirest.get url
    end
    respond_to do |format|
      if @sm.save
        format.html { redirect_to @sm, notice: 'Sm was successfully created.' }
        format.json { render :show, status: :created, location: @sm }
      else
        format.html { render :new }
        format.json { render json: @sm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sms/1
  # PATCH/PUT /sms/1.json
  def update
    respond_to do |format|
      if @sm.update(sm_params)
        format.html { redirect_to @sm, notice: 'Sm was successfully updated.' }
        format.json { render :show, status: :ok, location: @sm }
      else
        format.html { render :edit }
        format.json { render json: @sm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sms/1
  # DELETE /sms/1.json
  def destroy
    @sm.destroy
    respond_to do |format|
      format.html { redirect_to sms_url, notice: 'Sm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sm
      @sm = Sm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sm_params
      params.require(:sm).permit(:title, :message, :to)
    end

    def generate_url(sm, emp)
      ENV['SMS_PROVIDER_URL'] + '?user=' + ENV['SMS_USERNAME'] + '&pwd=' + ENV['SMS_PASSWORD'] + '&sender=' + ENV['SMS_SENDER'] + '&reciever=' + emp.number + '&msg-data=' + URI.encode(sm.message) + '&response=' + 'string'
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :package %><br>
    <%= f.number_field :package %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_import_employees.html.erb
<div class="modal bnr-modal fade" id="uploadStudentsModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
             <div class="row">
                <div class="col-xs-10">
                  <h2 id="time-status">Upload Students</h2>        
                </div>
                <div class="col-xs-2">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
              </div>
          </div>
          <div class="modal-body modal-spa" id="create-class-div">
    	      <div class="row">
    	        <div class="col-xs-6">
    	          <h4></h4>
    	        </div>
    	      </div>
    	      <div class="row">
    	      	<div classs="col-md-3">
    	      		<div class="quiz-form">
            	        <%= form_tag add_employee_companies_path, multipart: true do %>
            	          <%= file_field_tag :file, class:'btn btn-logout' %><br>
            	          <%= hidden_field_tag :company_id, @company.id %>
                        <%= submit_tag "Import",class:'btn btn-default'%>
    	       	        <% end %>
    	          </div>
    	      	</div>
    	      </div>
         </div>
      </div>
    </div>
  </div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Companies</h1>

  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Package</th>
        <th colspan="4">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
      <tr>
        <td><%= company.title %></td>
        <td><%= company.package %></td>
        <td>
          <span><%= link_to 'Show', company %></span> 
          <span><%= link_to 'Edit', edit_company_path(company) %></span>
          <span><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Company', new_company_path, class: 'btn btn-success'  %>
  
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
		<strong>Title:</strong>
		<%= @company.title %>
	</p>

	<p>
		<strong>Package:</strong>
		<%= @company.package %>
	</p>

	<h3>Employees</h3>
	
	<table class='table table-striped'>
		<thead>
			<tr>
				<th>Name</th>
				<th>Number</th>
				<th colspan="4">Actions</th>
			</tr>
		</thead>
		
		<tbody>
			<% @employees.each do |emp| %>
			<tr>
				<td><%= emp.name %></td>
				<td><%= emp.number %></td>
				<td>
						<span class='label label-danger'>Destroy</span>
						<!-- delete employee -->
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'Edit', edit_company_path(@company) %> |
	<%= link_to 'Back', companies_path %>
	<button id='btn' class='btn btn-default' style="cursor: pointer;"> Upload Employe </button>

	<div class="row">
		<div classs="col-md-3 employee-div">
			<h3>Upload Employee</h3>
			<div class="quiz-form">
				<%= form_tag add_employee_companies_path, multipart: true do %>
				<%= file_field_tag :file, class:'btn btn-logout' %><br>
				<%= hidden_field_tag :company_id, @company.id %>
				<%= submit_tag "Import",class:'btn btn-default'%>
				<% end %>
			</div>
		</div>
	</div>

</div>

<script>
	$(document).ready(function() {
		$('#btn').click(function() {
			alert('inside')
			$('.quiz-form').show();
		});
	});

</script>

<style>
	.quiz-form {
		display: none;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AugmentCare Apps</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%=link_to "Corporates", companies_path%></a></li>
       <li><%=link_to "Sms", sms_path%></a></li>
        <%if user_signed_in?%>
          <li><%=link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <%else%>
           <li><%=link_to "Sign in", new_user_session_url%></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>	

<%= yield %>
</div>
</body>
</html>

app/views/sms/_form.html.erb
<div class="container">
  <%= form_for(@sm) do |f| %>
  <% if @sm.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@sm.errors.count, "error") %> prohibited this sm from being saved:</h2>

    <ul>
      <% @sm.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.select :to, options_for_select(Company.all.pluck(:title, :id)),{include_blank: true}, {class: 'form-control'}  %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/sms/edit.html.erb
<h1>Editing Sm</h1>

<%= render 'form' %>

<%= link_to 'Show', @sm %> |
<%= link_to 'Back', sms_path %>

app/views/sms/index.html.erb
<div class="">
  <p id="notice"><%= notice %></p>

  <h1>Listing Sms</h1>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Company</th>
        <th>Employee</th>
        <th>Message</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @sms.each do |sm| %>
      <tr>
        <td><%= sm.title %></td>
        <td><%= Company.find(sm.to).title %></td>
        <td><%= Company.find(sm.to).employees.count %></td>
        <td width='50%'><%= sm.message.capitalize %></td>
        <td>
          <span><%= link_to 'Show', sm, class: 'label label-default'%></span>
          <span><%= link_to 'Destroy', sm, method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-danger' %></span>
        </td>  
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<%= link_to 'New Sm', new_sm_path, class: 'btn btn-success' %>  
</div>

app/views/sms/new.html.erb
<h1>New Sm</h1>

<%= render 'form' %>

<%= link_to 'Back', sms_path %>

app/views/sms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sm.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @sm.message %>
</p>

<p>
  <strong>To:</strong>
  <%= @sm.to %>
</p>

<%= link_to 'Edit', edit_sm_path(@sm) %> |
<%= link_to 'Back', sms_path %>